/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/chat`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/home`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/profile`; params?: Router.UnknownInputParams; } | { pathname: `/vender/chat`; params?: Router.UnknownInputParams; } | { pathname: `/vender/home`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/home`; params?: Router.UnknownOutputParams; } | { pathname: `/buyer/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/vender/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/vender/home`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/buyer/chat${`?${string}` | `#${string}` | ''}` | `/buyer/edit-profile${`?${string}` | `#${string}` | ''}` | `/buyer/home${`?${string}` | `#${string}` | ''}` | `/buyer/profile${`?${string}` | `#${string}` | ''}` | `/vender/chat${`?${string}` | `#${string}` | ''}` | `/vender/home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/chat`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/home`; params?: Router.UnknownInputParams; } | { pathname: `/buyer/profile`; params?: Router.UnknownInputParams; } | { pathname: `/vender/chat`; params?: Router.UnknownInputParams; } | { pathname: `/vender/home`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
