/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddProduct`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BuyerCart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VendorOrders`; params?: Router.UnknownInputParams; } | { pathname: `/utils/Storage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/AddProduct`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/BuyerCart`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Cart`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Search`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/VendorOrders`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/Storage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ProductCard${`?${string}` | `#${string}` | ''}` | `/screens/AddProduct${`?${string}` | `#${string}` | ''}` | `/screens/BuyerCart${`?${string}` | `#${string}` | ''}` | `/screens/Cart${`?${string}` | `#${string}` | ''}` | `/screens/Login${`?${string}` | `#${string}` | ''}` | `/screens/Register${`?${string}` | `#${string}` | ''}` | `/screens/Search${`?${string}` | `#${string}` | ''}` | `/screens/VendorOrders${`?${string}` | `#${string}` | ''}` | `/utils/Storage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProductCard`; params?: Router.UnknownInputParams; } | { pathname: `/screens/AddProduct`; params?: Router.UnknownInputParams; } | { pathname: `/screens/BuyerCart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VendorOrders`; params?: Router.UnknownInputParams; } | { pathname: `/utils/Storage`; params?: Router.UnknownInputParams; };
    }
  }
}
